language: node_js
node_js:
  - node
git:
  depth: 1
branches:
  only:
    - master
    - stage
install:
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  app: personal-website
  api_key:
    secure: gIu1aSrA4amI8PtR4lu+OTHnRMMBaS/afxC9uaHKkmTEuqqf1bPIv2hRrLOyPnHLIvnkI2kSMVWl7P21XkY3M0C94tbFCmakC3AEPKiq9qPLw9c9MFEYEavEL7eL15CqC6WKhxrZqijDvqeCm7+EkEIL+y3TtO+ymFCbShYkwaF4edmQIkFU0Y8ANzokB1luzUlXuiAxoLMGf4Aun/wgG5LaCYV1KyMbVQE7/2hR4GSFm7RYWBnSvbwk7A5kBH1Kh3wZRJVzD8d4psC4bFtpeCvuShyIAvnvALzKlJaVWiEy6tdBcaxb0tgxI9Y8PCoweUhIIKzE+KnLTKdM9XED97Uhuenu/lkrfi4G+jBV2HEsMH8njCXY3bUmITaTMr0iGjvjug6RmMNjBNkvsZaGCN8AVVmcdZ+HkPYErSLoj8AxBnozdvpAtHTdrTrLDHI1tOryjYs+IWwoKzFIE447Tq9vqpWF8cgfP9ngV2Q0kM4FnYy/MM9Yo2xjk6t/r7BBjnUTaWbZlQN0KuDvSDSkOxnlHUIuielGSf2gGhxKSLrI9818ClSX3hgm1bN3ogpIwF2fJ+oU69ZO37kBo8LV46a1AKoFbZX4SpFhVj+V9DogRhi0nF4sXvAHfdbHwjCa4f1xFrtWyRCOh5AiF3LpFkqRI2fRmV2paXd38BYXjpY=
